"""状态默认aa

Revision ID: 04f2c7e5af74
Revises: 481a9661e787
Create Date: 2020-03-02 04:19:52.597848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f2c7e5af74'
down_revision = '481a9661e787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.Enum('正常', '删除'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
