"""状态默认博客

Revision ID: 3e234983156d
Revises: 38d71aa4e650
Create Date: 2020-03-02 04:53:44.984533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e234983156d'
down_revision = '38d71aa4e650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('status', sa.Enum('正常', '草稿', '删除'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'status')
    # ### end Alembic commands ###
