"""状态默认a

Revision ID: 481a9661e787
Revises: 5d41f72e19f9
Create Date: 2020-03-02 04:19:40.114030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '481a9661e787'
down_revision = '5d41f72e19f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', mysql.ENUM('正常', '删除', collation='utf8mb4_unicode_ci'), nullable=True))
    # ### end Alembic commands ###
