"""状态

Revision ID: a7fb7c961067
Revises: 13bd3b04a7ec
Create Date: 2020-03-02 04:18:23.848437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7fb7c961067'
down_revision = '13bd3b04a7ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('status', mysql.ENUM('正常', '删除', collation='utf8mb4_unicode_ci'), nullable=True))
    # ### end Alembic commands ###
