"""删除搜索历史的外键

Revision ID: eafe5a09bcc5
Revises: e6cb764b8c2e
Create Date: 2020-03-08 18:52:54.984053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eafe5a09bcc5'
down_revision = 'e6cb764b8c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comment_create_time', table_name='comment')
    op.drop_index('ix_message_create_time', table_name='message')
    op.drop_constraint('search_history_ibfk_1', 'search_history', type_='foreignkey')
    op.drop_column('search_history', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('search_history_ibfk_1', 'search_history', 'user', ['user_id'], ['id'])
    op.create_index('ix_message_create_time', 'message', ['create_time'], unique=False)
    op.create_index('ix_comment_create_time', 'comment', ['create_time'], unique=False)
    # ### end Alembic commands ###
