"""修改数据库asss

Revision ID: eb8b6b2fe3a4
Revises: faded9dd2a27
Create Date: 2020-03-02 05:25:37.983269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb8b6b2fe3a4'
down_revision = 'faded9dd2a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True))
    # ### end Alembic commands ###
