"""修改数据库asssaw

Revision ID: f84ec3a7ad97
Revises: eb8b6b2fe3a4
Create Date: 2020-03-02 05:25:53.321880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84ec3a7ad97'
down_revision = 'eb8b6b2fe3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('name', sa.String(length=32), nullable=False))
    op.create_unique_constraint(None, 'tag', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_column('tag', 'name')
    # ### end Alembic commands ###
