"""修改数据库

Revision ID: faded9dd2a27
Revises: 3e234983156d
Create Date: 2020-03-02 05:12:58.295889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'faded9dd2a27'
down_revision = '3e234983156d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_to_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('tag_ibfk_1', 'tag', type_='foreignkey')
    op.drop_column('tag', 'blog_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('blog_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('tag_ibfk_1', 'tag', 'blog', ['blog_id'], ['id'])
    op.drop_table('blog_to_tag')
    # ### end Alembic commands ###
